"""initial

Revision ID: c71378706e38
Revises: 
Create Date: 2026-01-05 22:29:40.168172
"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'c71378706e38'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure enum types use lowercase values to match model enums.
    op.execute("DROP TYPE IF EXISTS appliesto CASCADE")
    op.execute("DROP TYPE IF EXISTS groupvisibility CASCADE")
    op.execute("DROP TYPE IF EXISTS groupstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS costtype CASCADE")
    op.execute("DROP TYPE IF EXISTS membershiprole CASCADE")
    op.execute("DROP TYPE IF EXISTS joinstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS verificationstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS userrole CASCADE")

    op.execute("CREATE TYPE appliesto AS ENUM ('male', 'female', 'other', 'all')")
    op.execute("CREATE TYPE groupvisibility AS ENUM ('public', 'invite_only')")
    op.execute("CREATE TYPE groupstatus AS ENUM ('open', 'full', 'closed', 'completed')")
    op.execute("CREATE TYPE costtype AS ENUM ('free', 'shared', 'fully_paid', 'custom')")
    op.execute("CREATE TYPE membershiprole AS ENUM ('creator', 'member')")
    op.execute("CREATE TYPE joinstatus AS ENUM ('requested', 'approved', 'rejected')")
    op.execute("CREATE TYPE verificationstatus AS ENUM ('pending', 'verified', 'rejected')")
    op.execute("CREATE TYPE userrole AS ENUM ('user', 'admin')")

    op.add_column('group_requirements', sa.Column('additional_requirements', sa.Text(), nullable=True))
    op.add_column('group_requirements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('group_requirements', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('group_requirements', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('group_requirements', 'applies_to',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('male', 'female', 'other', 'all', name='appliesto'),
               existing_nullable=True,
               postgresql_using='lower(applies_to)::appliesto')
    op.add_column('groups', sa.Column('description', sa.Text(), nullable=False, server_default=''))
    op.add_column('groups', sa.Column('location', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('groups', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('groups', sa.Column('min_participants', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('rules', sa.Text(), nullable=True))
    op.add_column('groups', sa.Column('expectations', sa.JSON(), nullable=True))
    op.add_column('groups', sa.Column('visibility', sa.Enum('public', 'invite_only', name='groupvisibility'), nullable=True))
    op.add_column('groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('groups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memberships', sa.Column('role', sa.Enum('creator', 'member', name='membershiprole'), nullable=True))
    op.add_column('memberships', sa.Column('join_status', sa.Enum('requested', 'approved', 'rejected', name='joinstatus'), nullable=True))
    op.add_column('memberships', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memberships', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('memberships', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('memberships', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_memberships_user_group', 'memberships', ['user_id', 'group_id'])
    op.drop_column('memberships', 'status')
    op.add_column('users', sa.Column('sexual_orientation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location_country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus'), server_default='pending', nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userrole'), server_default='user', nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('users', 'is_verified')
    op.alter_column('group_requirements', 'created_at', server_default=None)
    op.alter_column('group_requirements', 'updated_at', server_default=None)
    op.alter_column('groups', 'description', server_default=None)
    op.alter_column('groups', 'created_at', server_default=None)
    op.alter_column('groups', 'updated_at', server_default=None)
    op.alter_column('memberships', 'created_at', server_default=None)
    op.alter_column('memberships', 'updated_at', server_default=None)
    op.alter_column('users', 'verification_status', server_default=None)
    op.alter_column('users', 'role', server_default=None)
    op.alter_column('users', 'updated_at', server_default=None)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'location_lng')
    op.drop_column('users', 'location_lat')
    op.drop_column('users', 'location_country')
    op.drop_column('users', 'location_city')
    op.drop_column('users', 'sexual_orientation')
    op.add_column('memberships', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_memberships_user_group', 'memberships', type_='unique')
    op.drop_column('memberships', 'deleted_at')
    op.drop_column('memberships', 'updated_at')
    op.drop_column('memberships', 'created_at')
    op.drop_column('memberships', 'joined_at')
    op.drop_column('memberships', 'join_status')
    op.drop_column('memberships', 'role')
    op.drop_column('groups', 'deleted_at')
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'visibility')
    op.drop_column('groups', 'expectations')
    op.drop_column('groups', 'rules')
    op.drop_column('groups', 'min_participants')
    op.drop_column('groups', 'end_date')
    op.drop_column('groups', 'start_date')
    op.drop_column('groups', 'destination')
    op.drop_column('groups', 'location')
    op.drop_column('groups', 'description')
    op.alter_column('group_requirements', 'applies_to',
               existing_type=sa.Enum('male', 'female', 'other', 'all', name='appliesto'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('group_requirements', 'deleted_at')
    op.drop_column('group_requirements', 'updated_at')
    op.drop_column('group_requirements', 'created_at')
    op.drop_column('group_requirements', 'additional_requirements')
    # ### end Alembic commands ###
